/**
 * Separate sidebars for each section.
 */

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // About: explicitly list top-level docs only
  aboutSidebar: [
   {
    type: 'autogenerated',
    dirName: 'about',
   }
  ],

  // Buyer
  buyerSidebar: [
    {
      type: 'autogenerated',
      dirName: 'buyer',
    },
  ],

  // Seller
  sellerSidebar: [
    {
      type: 'autogenerated',
      dirName: 'seller',
    },
  ],

  // Agent
  agentSidebar: [
    {
      type: 'autogenerated',
      dirName: 'agent',
    },
  ],

  // Developer
  developerSidebar: [
    {
      type: 'autogenerated',
      dirName: 'developer',
    },
  ],
  vacanciesSidebar: [
    {
      type: 'autogenerated',
      dirName: 'vacancies',
    },
  ],
  releaseSidebar: [
   "releases",
  ],
};

module.exports = sidebars;


